# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(db_index=True, help_text='e.g. SP-CHK-20260822-00001', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text='Checkout page title', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('success_url', models.URLField(blank=True, default='')),
                ('cancel_url', models.URLField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the checkout session expires', null=True)),
                ('allowed_methods', models.JSONField(blank=True, default=list, help_text='List of PaymentMethod values allowed')),
                ('logo_url', models.URLField(blank=True, default='')),
                ('brand_color', models.CharField(blank=True, default='', max_length=20)),
                ('selected_method', models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('qr_code', 'QR Code'), ('wallet_transfer', 'Wallet Transfer'), ('phone_number', 'Phone Number'), ('hosted_checkout', 'Hosted Checkout'), ('payment_link', 'Payment Link')], default='', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='businesses.business')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='checkout_ch_busines_16ce89_idx'), models.Index(fields=['reference'], name='checkout_ch_referen_458fa2_idx')],
            },
        ),
    ]
