# Generated by Django 5.1.15 on 2026-08-22 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='businesses.business'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash', 'environment'], name='accounts_ap_key_has_4df8d0_idx'),
        ),
    ]
