# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', models.CharField(db_index=True, help_text='API key hash, user ID, or IP', max_length=200)),
                ('window_start', models.DateTimeField()),
                ('request_count', models.IntegerField(default=0)),
                ('request_limit', models.IntegerField(default=1000, help_text='Max requests per window')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['identifier', 'window_start'], name='developer_r_identif_441d22_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('request_id', models.CharField(db_index=True, help_text='Unique request identifier', max_length=100, unique=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='production', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='accounts.apikey')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to='businesses.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='developer_a_busines_3604b0_idx'), models.Index(fields=['api_key', '-created_at'], name='developer_a_api_key_a76ba7_idx'), models.Index(fields=['request_id'], name='developer_a_request_b45d4c_idx'), models.Index(fields=['path', 'method'], name='developer_a_path_91a72a_idx'), models.Index(fields=['status_code'], name='developer_a_status__e16f96_idx')],
            },
        ),
    ]
