# Generated by Django 5.1.15 on 2026-08-22 03:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('external_customer_id', models.CharField(blank=True, default='', help_text="Business's own customer ID", max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(db_index=True, help_text='Internal reference e.g. SP-TXN-20260822-00009281', max_length=100, unique=True)),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', help_text="Business's own reference e.g. ORDER-92882", max_length=100)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', help_text="Provider's reference e.g. SEL-XXXXXXXX", max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross amount', max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total fee charged', max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount after fees', max_digits=18)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('refund', 'Refund'), ('fee', 'Fee'), ('reversal', 'Reversal'), ('settlement', 'Settlement')], default='payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='pending', max_length=20)),
                ('provider', models.CharField(blank=True, default='', help_text='e.g. selcom', max_length=50)),
                ('provider_metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific data')),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Business-provided metadata')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='Client-provided key to prevent duplicates', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='businesses.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.customer')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'phone'], name='transaction_busines_2d5321_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['business', 'email'], name='transaction_busines_5993dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('business', 'external_customer_id')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['business', 'status'], name='transaction_busines_7115d3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='transaction_referen_923a88_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_reference'], name='transaction_externa_6c3fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider_reference'], name='transaction_provide_4c9af9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['idempotency_key'], name='transaction_idempot_68455c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status'], name='transaction_type_983c49_idx'),
        ),
    ]
