# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(db_index=True, help_text='Internal reference e.g. SP-WDR-20260822-00001', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount after fees', max_digits=18)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('destination_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('qr_code', 'QR Code'), ('wallet_transfer', 'Wallet Transfer'), ('phone_number', 'Phone Number'), ('hosted_checkout', 'Hosted Checkout'), ('payment_link', 'Payment Link')], default='mobile_money', help_text='Where the money is being sent', max_length=30)),
                ('destination_account', models.CharField(help_text='Phone number, bank account, etc.', max_length=100)),
                ('destination_name', models.CharField(blank=True, default='', max_length=200)),
                ('destination_metadata', models.JSONField(blank=True, default=dict, help_text='Bank name, branch, etc.')),
                ('provider', models.CharField(blank=True, default='', help_text='e.g. selcom', max_length=50)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('approval_tier', models.CharField(blank=True, default='', help_text='auto, officer, senior', max_length=20)),
                ('approval_note', models.TextField(blank=True, default='')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_approved', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='businesses.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_created', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_rejected', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Linked transaction record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='transactions.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='withdrawals_busines_68a6df_idx'), models.Index(fields=['reference'], name='withdrawals_referen_19ef98_idx'), models.Index(fields=['provider_reference'], name='withdrawals_provide_170a0c_idx'), models.Index(fields=['status', 'type'], name='withdrawals_status_7a5458_idx')],
            },
        ),
    ]
