# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fee_type', models.CharField(choices=[('platform', 'Platform Fee'), ('provider', 'Provider Fee'), ('withdrawal', 'Withdrawal Fee'), ('transfer', 'Transfer Fee'), ('refund', 'Refund Fee'), ('settlement', 'Settlement Fee')], default='platform', max_length=20)),
                ('transaction_type', models.CharField(choices=[('payment', 'Payment'), ('transfer', 'Transfer'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('refund', 'Refund'), ('fee', 'Fee'), ('reversal', 'Reversal'), ('settlement', 'Settlement')], default='payment', max_length=20)),
                ('provider', models.CharField(blank=True, default='', help_text='e.g. selcom. If blank, applies to all providers.', max_length=50)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Percentage of the transaction amount (e.g. 0.0190 = 1.9%)', max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fixed fee amount added to the percentage', max_digits=18)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum fee that will be charged', max_digits=18)),
                ('maximum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum fee cap. 0 means no cap.', max_digits=18)),
                ('payer', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='business', help_text='Who pays the fee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are evaluated first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='If null, this rule applies to all businesses (default rule)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='businesses.business')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['business', 'transaction_type', 'is_active'], name='fees_feerul_busines_74c6bb_idx'), models.Index(fields=['fee_type', 'is_active'], name='fees_feerul_fee_typ_7e01c0_idx'), models.Index(fields=['provider', 'transaction_type'], name='fees_feerul_provide_4201f9_idx')],
            },
        ),
    ]
