# Generated by Django 5.1.15 on 2026-08-22 03:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='wallets_wal_busines_5da70d_idx')],
                'unique_together': {('business', 'currency')},
            },
        ),
    ]
