# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('batch_reference', models.CharField(db_index=True, help_text='e.g. SP-REC-20260822-001', max_length=100, unique=True)),
                ('provider', models.CharField(default='selcom', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('total_salama_records', models.IntegerField(default=0)),
                ('total_provider_records', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('unmatched_count', models.IntegerField(default=0)),
                ('flagged_count', models.IntegerField(default=0)),
                ('total_matched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_unmatched_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('resolved', 'Resolved'), ('flagged', 'Flagged')], default='unmatched', max_length=20)),
                ('salama_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('salama_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('salama_status', models.CharField(blank=True, default='', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('provider_status', models.CharField(blank=True, default='', max_length=20)),
                ('mismatch_type', models.CharField(blank=True, default='', help_text='amount_mismatch, status_mismatch, missing_in_provider, missing_in_salama', max_length=50)),
                ('mismatch_details', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reconciliation.reconciliationbatch')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reconciliation_records', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_records', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reconciliationbatch',
            index=models.Index(fields=['provider', 'status'], name='reconciliat_provide_9157df_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationbatch',
            index=models.Index(fields=['date_from', 'date_to'], name='reconciliat_date_fr_c15144_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['batch', 'status'], name='reconciliat_batch_i_253237_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['salama_reference'], name='reconciliat_salama__80b209_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationrecord',
            index=models.Index(fields=['provider_reference'], name='reconciliat_provide_f9aa25_idx'),
        ),
    ]
