# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Short code encoded in the QR', max_length=20, unique=True)),
                ('type', models.CharField(choices=[('static', 'Static QR'), ('dynamic', 'Dynamic QR')], default='static', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null for open-amount static QR', max_digits=18, null=True)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('qr_image_url', models.URLField(blank=True, default='')),
                ('qr_data', models.TextField(blank=True, default='', help_text='Raw data encoded in the QR')),
                ('expires_at', models.DateTimeField(blank=True, help_text='For dynamic QR codes', null=True)),
                ('scan_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='businesses.business')),
                ('transaction', models.ForeignKey(blank=True, help_text='Linked transaction for dynamic QR codes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='qr_payments_busines_3ab6e4_idx'), models.Index(fields=['code'], name='qr_payments_code_dcae52_idx'), models.Index(fields=['type', 'status'], name='qr_payments_type_675cc6_idx')],
            },
        ),
    ]
