# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('link_code', models.CharField(db_index=True, help_text='Short code in the URL', max_length=20, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null means customer enters amount', max_digits=18, null=True)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('title', models.CharField(help_text='What the payment is for', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('expired', 'Expired'), ('used', 'Used')], default='active', max_length=20)),
                ('is_single_use', models.BooleanField(default=False, help_text="If true, link becomes 'used' after one payment")),
                ('max_uses', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('use_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('success_url', models.URLField(blank=True, default='')),
                ('cancel_url', models.URLField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='payment_lin_busines_5dbf4b_idx'), models.Index(fields=['link_code'], name='payment_lin_link_co_cd0146_idx')],
            },
        ),
    ]
