# Generated by Django 5.1.15 on 2026-08-22 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_type', models.CharField(help_text='e.g. velocity_check, amount_threshold, time_window', max_length=50)),
                ('parameters', models.JSONField(default=dict, help_text='Rule-specific parameters')),
                ('action', models.CharField(default='flag', help_text='flag, block, manual_review', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shilling'), ('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling')], default='TZS', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='If null, applies to all businesses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='businesses.business')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('velocity_breach', 'Velocity Breach'), ('amount_threshold', 'Amount Threshold'), ('suspicious_activity', 'Suspicious Activity'), ('blacklist_match', 'Blacklist Match'), ('manual_review', 'Manual Review')], default='manual_review', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0, help_text='0-100 risk score', max_digits=5)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='businesses.business')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_risk_events', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_events', to='transactions.transaction')),
                ('risk_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='risk.riskrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('entry_type', models.CharField(choices=[('phone', 'Phone Number'), ('email', 'Email'), ('account', 'Account'), ('ip', 'IP Address')], max_length=20)),
                ('value', models.CharField(db_index=True, help_text='The phone, email, account, or IP to block', max_length=200)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(blank=True, help_text='If null, global blacklist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='businesses.business')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry_type', 'value', 'is_active'], name='risk_blackl_entry_t_cb7356_idx'), models.Index(fields=['business', 'is_active'], name='risk_blackl_busines_220e92_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='riskrule',
            index=models.Index(fields=['business', 'is_active'], name='risk_riskru_busines_2145ad_idx'),
        ),
        migrations.AddIndex(
            model_name='riskrule',
            index=models.Index(fields=['rule_type', 'is_active'], name='risk_riskru_rule_ty_77a833_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['business', 'is_resolved'], name='risk_riskev_busines_25d1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='riskevent',
            index=models.Index(fields=['risk_level', 'is_resolved'], name='risk_riskev_risk_le_d04a4e_idx'),
        ),
    ]
